healthcare_claims_elt:   
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: HC_CLAIMS
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: ""
      threads: 4
      client_session_keep_alive: false
